/controller_manager:
  ros__parameters:
    fault_controller:
      type: picknik_reset_fault_controller/PicknikResetFaultController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    robotiq_gripper_controller:
      type: position_controllers/GripperActionController
    twist_controller:
      type: picknik_twist_controller/PicknikTwistController
    update_rate: 1000
/joint_trajectory_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    command_interfaces:
    - position
    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.0
    joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
    state_interfaces:
    - position
    - velocity
    state_publish_rate: 100.0
/robotiq_gripper_controller:
  ros__parameters:
    allow_stalling: true
    default: true
    joint: robotiq_85_left_knuckle_joint
/twist_controller:
  ros__parameters:
    interface_names:
    - twist.linear.x
    - twist.linear.y
    - twist.linear.z
    - twist.angular.x
    - twist.angular.y
    - twist.angular.z
    joint: tcp
